## **Numpy Basics**
1. Numpy is the core library for scientific computing in Python and is used to perform computations on multi-dimensional data easily and effectively. 
1. Numpy provides a new data structure called arrays which allow efficient vector and matrix operations and a number of linear algebra operations

**Convert a list into an array using numpy**

In [2]:
import numpy as np #Import numpy package

a_list = [1,2,3,4]
a = np.array(a_list) #Convert list to numpy array
a

array([1, 2, 3, 4])

**Scalar, Vector, Matrix (Tensor)**

In [ ]:
a = np.array(1)  # define scalar
print('a\n', a.__repr__())
print('shape of a: ', a.shape)
print('dimension of a: ', a.ndim)

b = np.array([1, 2, 3, 4, 5]) # define vector
print('b\n', b.__repr__())
print('shape of b: ', b.shape)
print('dimension of b: ', b.ndim)

c = np.array([[1, 2, 3], [4, 5, 6]]) # define matrix
print('c\n',c.__repr__())
print('shape of c: ', c.shape)
print('dimension of c: ', c.ndim)

**Create array obejects using arange(), zeros(), ones(), linspace() methods**

In [ ]:
#Numpy also provides many methods to create arrays.

a = np.arange(0, 10, 1)

print('created from .arange() method: ', a)

a = np.zeros(10)
print('created from .zeros() method: ', a)

a = np.ones(10)
print('created from .ones() method: ', a)

a = np.linspace(0,2,9)
print('created from .linspace() method: ', a)

In [ ]:
# Convert datatype of elements
a = np.arange(10)
print(a.dtype)   # original datatype

b = a.astype(np.float) # convert to float
print(b.dtype)

In [5]:
# We can also make multidimensional arrays.

np.random.seed(0) # random seed for reproducibility
a = np.arange(16).reshape(2,8) #reshape function gives a new shape to an array without changing its data
b = np.ones ((2,8))
c = np.random.random((2,8)) #Create an array randomly

print('created from .reshape() method: \n', a.__repr__())
print()
print('created from .ones() method: \n', b.__repr__())
print()
print('created from .random.random() method: \n', c.__repr__())

created from .reshape() method: 
 array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

created from .ones() method: 
 array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

created from .random.random() method: 
 array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
        0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492, 0.56804456,
        0.92559664, 0.07103606, 0.0871293 ]])


In [ ]:
#You can check the dimension or size of arrays
a = np.random.random((2, 4, 5))  # dimensional array
a

In [ ]:
print('dimension of array: ', a.ndim)
print('shape of array', a.shape) 
print('number of row: ', a.shape[0])
print('number of column: ', a.shape[1])
print('total number of elements in array: ', a.size)
print('data type of elements: ', a.dtype)

In [ ]:
# 4 dimensional array
b = np.random.random((2, 3, 4, 5))
print('b:\n', b.__repr__())

**Indexing & Slicing**

In [ ]:
#In a similar way to Python lists, numpy arrays can be indexed.
a = np.ones(5)
a[0] = 6
a[4] = 2
a

In [ ]:
a[-1]  # -1 indicates last element

In [ ]:
a[0:-1] # include 0 index and exclude -1 (last) index of element

In [ ]:
# Create (3, 4) shape of tensor
a = np.arange(1, 13).reshape(3, 4)
a

In [ ]:
a[0] # indexing the first row 

In [ ]:
a[0, 1] # indexing second element of the first row

In [ ]:
a[0, 1:3] # slicing the first row from 1 to 3 (exclusive)

In [ ]:
a[0:3:2, 1:4:2] # slicing with respect to both 1 , 2 - dimensional elements

In [ ]:
# slicing with multi-dimensional array
a = np.arange(30).reshape(2, 3, 5)
a

In [ ]:
a[0] # first matrix element

In [ ]:
a[0, 1, :] # second row of first matrix element

In [ ]:
a[0, :, 2] # third column of first matrix element

In [ ]:
a[1, 0:3:2, 1:4:2] # slicing with respect to both 2 , 3 - dimensional elements

In [ ]:
# add an additional dimension
a[None].shape  # add extra dimension in first dim

In [ ]:
a[:, None].shape # add in second dim

In [ ]:
a[..., None].shape  # add in last dim

In [ ]:
a[..., None, :].shape  # add in second last dim

**Numpy Operations**

In [3]:
# Basic mathematical functions in the numpy module are available and operate elementwise on arrays.
# support all basic numerical operations such as +. -. *, /, ** ..
a = np.arange(0,3,0.5)
b = np.arange(1,4,0.5)
print('a:\n', a.__repr__())
print('b:\n', b.__repr__(), end='\n')

print('array a: ', a)
print('a + 5: ', a + 5)
print('a^2: ', a ** 2)
print('cos(a): ', np.cos(a))
print('logical operation of a < 1: ', a < 1)

a:
 array([0. , 0.5, 1. , 1.5, 2. , 2.5])
b:
 array([1. , 1.5, 2. , 2.5, 3. , 3.5])
array a:  [0.  0.5 1.  1.5 2.  2.5]
a + 5:  [5.  5.5 6.  6.5 7.  7.5]
a^2:  [0.   0.25 1.   2.25 4.   6.25]
cos(a):  [ 1.          0.87758256  0.54030231  0.0707372  -0.41614684 -0.80114362]
logical operation of a < 1:  [ True  True False False False False]


In [4]:
#Unlike MATLAB, operator * is not matrix multiplication but elementwise multiplication.
print('array a: ', a)
print('array b: ', b)
a * b

array a:  [0.  0.5 1.  1.5 2.  2.5]
array b:  [1.  1.5 2.  2.5 3.  3.5]


array([0.  , 0.75, 2.  , 3.75, 6.  , 8.75])

In [ ]:
# Instead, we use the dot function to compute inner products of vectors, 
np.dot(a, b)

In [ ]:
#You can perform matrix operations

a = np.array([[2,5],[1,2]])
b = np.array([[2,1],[5,7]])

np.matmul(a,b) # matrix multiplication

In [ ]:
# you can also use np.dot() method and @ keyword to compute matrix multiplication (@ works in python3.x version)
np.dot(a, b)

In [ ]:
a@b

In [ ]:
a.transpose() #transpose the array

In [ ]:
c = np.arange(18).reshape(3,6)
c

In [ ]:
# using np.ndarray.method()
print('max value of each column: ', c.max(axis = 0)) # max of each column
print('min value of each row:', c.min(axis = 1)) # min of each row
print('sums of each row:', c.sum(axis = 1)) # sum of each row
print('sums of all elements:', c.sum()) # sum of all elements
print('max value of array (matrix) c:', c.max()) # max of c

In [ ]:
# you can also use np.method()
np.sum(c, axis=0)

In [ ]:
np.max(c)

In [ ]:
# take operation while keeping dimension
np.sum(c, axis=0, keepdims=True)

In [ ]:
np.sum(c, axis=1, keepdims=True)

**Broadcasting**

In [ ]:
#Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when computing mathematical operations.

a = np.arange(18).reshape((3,6))
a # (3, 6) shape

In [ ]:
a * 5  # multiply with scalar -> convert to (3, 6) shape

In [ ]:
a * np.arange(6) # multiply with (6) shape -> also convert to (3, 6) shape

In [ ]:
b = np.arange(6)
print('b\n', b.__repr__())  # (6,) shape
c = np.arange(3).reshape(3, 1)
print('c\n', c.__repr__())  # (3, 1) shape

In [ ]:
b * c

In [ ]:
# Broadcasting with multidimensional arrays
a = np.arange(15).reshape(5, 1, 3, 1)
b = np.arange(8).reshape(2, 1, 4)
print('shape of a: ', a.shape)
print('shape of b: ', b.shape)

In [ ]:
# check dimension of a * b
(a * b).shape

In [ ]:
# Question: How machanism of broadcasting works?
# does it work for (5, 1, 3, 2) with (2, 1, 4) shape of tensor? -> No (why?)

**Stacking Arrays**

In [ ]:
#You can stack arrays horizontally or vertically

a = np.arange(12).reshape(3, 4)
print('a: \n', a.__repr__())
b = np.ones((2, 4))
print('b: \n', b.__repr__())
c = np.ones((3, 2))
print('c: \n', c.__repr__())

In [ ]:
np.vstack((a,b)) # stack array vertically

In [ ]:
np.hstack((a,c)) # stack array horizontally

**Boolean Array Indexing (Masking)**

In [ ]:
a = np.arange(1, 10).reshape(3, 3)
print('a: \n', a.__repr__())

In [ ]:
# Support element-wise logical operation (return as True or False)
even = a % 2 == 0
print(even.__repr__())

In [ ]:
# indexing the elements corresponding to its True boolean index and return as a rank 1 array 
a[even]

**Copy in numpy**

In [ ]:
#There are 3 cases of copying ndarray in numpy

#Case 1

a = np.zeros((2,2))
b = a #No copy at all # Share both the data and properties(e.g., dimension of array)
print('b: \n', b.__repr__())

b[1,1] = 1
print('b: \n', b.__repr__())
print('a: \n', a.__repr__()) # a is also changed


b.shape = (1,4)
print('shape of a: ', a.shape) #The shape of a is also changed

In [ ]:
#Case 2 : Shallow copy

a = np.zeros((2,2))
b = a.view() #Shallow copy # Share the data but not properties(e.g., dimension of array)
print('b: \n', b.__repr__())

b[1,1] = 1
print('b: \n', b.__repr__())
print('a: \n', a.__repr__()) # a is also changed!!

b.shape = (1,4)
print('shape of a: ', a.shape) #The shape of a is not changed

In [ ]:
#Case 3 : Deep copy

a=np.zeros((2,2))
c = a.copy() #Deep copy # Create an independet variable not sharing both the data and properties
print('c: \n', c.__repr__())

c[1,1] =1
print('c: \n', c.__repr__())
print('a: \n', a.__repr__()) # a is not changed

### References

https://numpy.org/

https://cs231n.github.io/python-numpy-tutorial/#numpy

http://aikorea.org/cs231n/python-numpy-tutorial/

https://nbviewer.jupyter.org/gist/FinanceData/274d1a051b8ef10379b35b3fa72dd931